databases:
  - name: kuma_lab
    databaseName: ã€Œkuma_lab
    user: kuma_lab
    region: singapore

services:
  - type: web
    name: kuma_lab
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kuma_lab
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
